CREATE TABLE IF NOT EXISTS UTXO(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TXID VARCHAR(150) NOT NULL,
    VOUT_IDX INTEGER NOT NULL,
    SCRIPT VARCHAR(150) NOT NULL,
    VALUE DECIMAL NOT NULL
);